# Generated by Django 3.1.5 on 2021-05-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DiaryApp', '__first__'),
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students', models.ManyToManyField(blank=True, to='LoginApp.KvantStudent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginApp.kvantteacher')),
            ],
        ),
        migrations.CreateModel(
            name='KvantLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminModule.kvantcourse')),
                ('mark', models.ManyToManyField(blank=True, to='DiaryApp.KvantLessonMark')),
                ('task', models.ManyToManyField(blank=True, to='DiaryApp.KvantLessonHomeWork')),
            ],
        ),
    ]
