# Generated by Django 3.1.5 on 2021-11-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KvantLesson',
        ),
    ]
