# Generated by Django 3.1.5 on 2021-11-12 06:08

import AdminModule.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantCourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=AdminModule.models.get_course_path)),
            ],
        ),
        migrations.AlterField(
            model_name='kvantcourse',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kvantcourse',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kvantcourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kvantcourse',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminModule.kvantcoursetype'),
        ),
    ]
