# Generated by Django 3.1.5 on 2021-11-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0002_auto_20211112_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantcourse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminModule.kvantcoursetype'),
        ),
    ]
