# Generated by Django 3.1.5 on 2021-11-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0003_auto_20211112_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvantcoursetype',
            old_name='type',
            new_name='name',
        ),
    ]
