# Generated by Django 3.1.5 on 2021-04-27 17:30

import SystemModule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=SystemModule.models.uploadFile)),
                ('upload_path', models.TextField(blank=True, default='files/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=SystemModule.models.uploadFile)),
                ('upload_path', models.TextField(blank=True, default='images/')),
            ],
        ),
    ]
