# Generated by Django 3.1.5 on 2021-03-27 07:49

import GeneralPage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudentPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('date', models.TimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, to='StudentPage.FileStorage')),
                ('image', models.ForeignKey(blank=True, default=GeneralPage.models.setDefaultImage, on_delete=models.SET(GeneralPage.models.setDefaultImage), to='StudentPage.imagestorage')),
            ],
        ),
        migrations.CreateModel(
            name='KvantMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('files', models.ManyToManyField(blank=True, to='StudentPage.FileStorage')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
