# Generated by Django 3.1.5 on 2021-03-28 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantnews',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
