# Generated by Django 3.1.5 on 2021-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralPage', '0002_auto_20210328_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantnews',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
