# Generated by Django 3.1.5 on 2022-04-17 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MailApp', '0001_initial'),
        ('NotificationApp', '0002_auto_20220416_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_link', models.TextField()),
                ('mail_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailApp.kvantmessage')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_notifications',
                'ordering': ['-id'],
            },
        ),
    ]
