# Generated by Django 3.1.5 on 2022-07-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectApp', '0002_auto_20220721_1807'),
        ('NotificationApp', '0003_projecttaskcreate_projecttaskupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamManipulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.kvantproject')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamKickNotification',
            fields=[
                ('teammanipulation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NotificationApp.teammanipulation')),
                ('manipulated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kicked', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kicker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('NotificationApp.teammanipulation',),
        ),
        migrations.CreateModel(
            name='TeamApplyNotification',
            fields=[
                ('teammanipulation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NotificationApp.teammanipulation')),
                ('manipulated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('NotificationApp.teammanipulation',),
        ),
    ]
