# Generated by Django 3.1.5 on 2022-04-18 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DiaryApp', '0004_auto_20220327_1037'),
        ('NotificationApp', '0003_mailnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_link', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaryApp.kvanthometask')),
            ],
            options={
                'db_table': 'task_notifications',
                'ordering': ['-id'],
            },
        ),
    ]
