# Generated by Django 3.1.5 on 2022-07-27 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectApp', '0002_auto_20220721_1807'),
        ('NotificationApp', '0004_teamapplynotification_teamkicknotification_teammanipulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamleaderChangeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manipulated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.kvantproject')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
