# Generated by Django 3.1.5 on 2021-08-26 09:25

import ProfileApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantaward',
            name='image',
            field=models.FileField(upload_to=ProfileApp.models.get_path),
        ),
    ]
