# Generated by Django 3.1.5 on 2022-02-18 13:59

import NewsApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tag', models.CharField(default='Общее', max_length=20)),
                ('image', models.ImageField(default=NewsApp.models.setDefaultImage, upload_to=NewsApp.models.getPath)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, to='CoreApp.FileStorage')),
            ],
            options={
                'db_table': 'kvant_news',
            },
        ),
    ]
