# Generated by Django 3.1.5 on 2022-08-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantnews',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
