# Generated by Django 3.1.5 on 2022-02-18 13:59

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=CoreApp.models.uploadFile)),
                ('upload_path', models.TextField(blank=True, default='files/')),
            ],
            options={
                'db_table': 'file_storage',
            },
        ),
    ]
