# Generated by Django 3.1.5 on 2021-03-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvantlessonhomework',
            old_name='student',
            new_name='students',
        ),
    ]
