# Generated by Django 3.1.5 on 2022-03-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_auto_20220216_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
