# Generated by Django 3.1.5 on 2022-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantprojecttask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
