# Generated by Django 3.1.5 on 2022-07-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedkvantproject',
            old_name='data',
            new_name='date',
        ),
    ]
