# Generated by Django 3.1.5 on 2022-03-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_auto_20220323_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantprojectmembershiprequest',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
