# Generated by Django 3.1.5 on 2021-05-20 17:12

import NewsApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SystemModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('style_content', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default=NewsApp.models.set_default_image, upload_to=NewsApp.models.get_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, to='SystemModule.FileStorage')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
