# Generated by Django 3.1.5 on 2021-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantnews',
            name='style_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kvantnews',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
