# Generated by Django 3.1.5 on 2021-08-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kvantnews',
            options={},
        ),
    ]
