# Generated by Django 3.1.5 on 2021-08-24 13:43

import NewsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20210823_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantnews',
            name='image',
            field=models.ImageField(default=NewsApp.models.set_default_image, error_messages={'invalid': 'Превью новости повреждено или не является изображением'}, upload_to=NewsApp.models.get_path),
        ),
        migrations.AlterField(
            model_name='kvantnews',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Заголовок невалиден', 'max_length': 'Заголовок не может превышать %(max)d (сейчас %(length)d).', 'required': 'Заголовок не может быть пустым.'}, max_length=100),
        ),
    ]
