# Generated by Django 3.1.5 on 2021-08-25 08:43

import NewsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_auto_20210824_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantnews',
            name='image',
            field=models.ImageField(default=NewsApp.models.set_default_image, upload_to=NewsApp.models.get_path),
        ),
        migrations.AlterField(
            model_name='kvantnews',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
