# Generated by Django 3.1.5 on 2021-11-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20210825_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvantnews',
            name='style_content',
        ),
    ]
