# Generated by Django 3.1.5 on 2021-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantlesson',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='DiaryApp.kvanthometask'),
        ),
    ]
