# Generated by Django 3.1.5 on 2021-05-08 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
        ('DiaryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantlessonmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginApp.kvantstudent'),
        ),
    ]
