# Generated by Django 3.1.5 on 2021-11-03 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0002_delete_kvantlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SystemModule', '0001_initial'),
        ('DiaryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminModule.kvantcourse')),
                ('files', models.ManyToManyField(blank=True, to='SystemModule.FileStorage')),
            ],
        ),
        migrations.CreateModel(
            name='KvantStudentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('ОТ', 'ОТ'), ('УП', 'УП')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KvantTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('files', models.ManyToManyField(blank=True, to='SystemModule.FileStorage')),
            ],
        ),
        migrations.CreateModel(
            name='KvantTaskWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('files', models.ManyToManyField(blank=True, to='SystemModule.FileStorage')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaryApp.kvantstudentwork')),
            ],
        ),
        migrations.RemoveField(
            model_name='kvantlessonmark',
            name='student',
        ),
        migrations.DeleteModel(
            name='KvantLessonHomeWork',
        ),
        migrations.DeleteModel(
            name='KvantLessonMark',
        ),
        migrations.AddField(
            model_name='kvanttask',
            name='works',
            field=models.ManyToManyField(blank=True, to='DiaryApp.KvantTaskWork'),
        ),
        migrations.AddField(
            model_name='kvantlesson',
            name='works',
            field=models.ManyToManyField(blank=True, to='DiaryApp.KvantStudentWork'),
        ),
    ]
