# Generated by Django 3.1.5 on 2021-11-09 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemModule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DiaryApp', '0002_auto_20211103_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantHomeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(default=None)),
                ('title', models.CharField(max_length=100)),
                ('files', models.ManyToManyField(blank=True, to='SystemModule.FileStorage')),
            ],
        ),
        migrations.CreateModel(
            name='KvantHomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('ОТ', 'ОТ'), ('УП', 'УП')], max_length=10)),
                ('files', models.ManyToManyField(blank=True, to='SystemModule.FileStorage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KvantLessonWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('ОТ', 'ОТ'), ('УП', 'УП')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='kvanttask',
            name='files',
        ),
        migrations.RemoveField(
            model_name='kvanttask',
            name='works',
        ),
        migrations.RemoveField(
            model_name='kvanttaskwork',
            name='files',
        ),
        migrations.RemoveField(
            model_name='kvanttaskwork',
            name='work',
        ),
        migrations.RemoveField(
            model_name='kvantlesson',
            name='works',
        ),
        migrations.AddField(
            model_name='kvantlesson',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='kvantlesson',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='KvantStudentWork',
        ),
        migrations.DeleteModel(
            name='KvantTask',
        ),
        migrations.DeleteModel(
            name='KvantTaskWork',
        ),
        migrations.AddField(
            model_name='kvanthometask',
            name='works',
            field=models.ManyToManyField(blank=True, to='DiaryApp.KvantHomeWork'),
        ),
        migrations.AddField(
            model_name='kvantlesson',
            name='mark',
            field=models.ManyToManyField(blank=True, to='DiaryApp.KvantLessonWork'),
        ),
        migrations.AddField(
            model_name='kvantlesson',
            name='task',
            field=models.OneToOneField(blank=True, default=None, on_delete=models.SET(None), to='DiaryApp.kvanthometask'),
        ),
    ]
