# Generated by Django 3.1.5 on 2021-11-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0001_initial'),
        ('DiaryApp', '0002_kvantlesson_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantlesson',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminModule.kvantcourse'),
        ),
    ]
