# Generated by Django 3.1.5 on 2021-11-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0003_auto_20211109_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantlesson',
            name='description',
            field=models.TextField(),
        ),
    ]
