# Generated by Django 3.1.5 on 2021-11-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0001_initial'),
        ('DiaryApp', '0003_kvantlesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantlesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminModule.kvantcourse'),
        ),
    ]
