# Generated by Django 3.1.5 on 2021-11-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0004_auto_20211111_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvantlesson',
            name='mark',
        ),
    ]
