# Generated by Django 3.1.5 on 2021-11-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0005_auto_20211109_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantlesson',
            name='task',
            field=models.OneToOneField(blank=True, on_delete=models.SET(None), to='DiaryApp.kvanthometask'),
        ),
    ]
