# Generated by Django 3.1.5 on 2021-11-12 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DiaryApp', '0005_remove_kvantlesson_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KvantLessonMarks',
            new_name='KvantLessonMark',
        ),
        migrations.AddField(
            model_name='kvantlesson',
            name='mark',
            field=models.ManyToManyField(blank=True, to='DiaryApp.KvantLessonMark'),
        ),
    ]
