# Generated by Django 3.1.5 on 2021-11-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0006_auto_20211112_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvanthometask',
            name='title',
        ),
    ]
