# Generated by Django 3.1.5 on 2021-03-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeacherPage', '0002_auto_20210327_1248'),
        ('LoginPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students', models.ManyToManyField(blank=True, to='LoginPage.KvantStudent')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='LoginPage.kvantteacher')),
            ],
        ),
        migrations.CreateModel(
            name='KvantLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.kvantcourse')),
                ('mark', models.ManyToManyField(blank=True, to='TeacherPage.KvantLessonMark')),
                ('task', models.ManyToManyField(blank=True, to='TeacherPage.KvantLessonHomeWork')),
            ],
        ),
    ]
