# Generated by Django 3.1.5 on 2021-03-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeacherPage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('participates', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KvantLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.kvantcourse')),
                ('mark', models.ManyToManyField(blank=True, to='TeacherPage.KvantLessonMark')),
                ('task', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='TeacherPage.kvantlessonhomework')),
            ],
        ),
    ]
