# Generated by Django 3.1.5 on 2021-03-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0002_kvantadmin_kvantstudent_kvantteacher'),
        ('AdminPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvantcourse',
            name='participates',
        ),
        migrations.AddField(
            model_name='kvantcourse',
            name='students',
            field=models.ManyToManyField(blank=True, to='LoginPage.KvantStudent'),
        ),
        migrations.AddField(
            model_name='kvantcourse',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='LoginPage.kvantteacher'),
        ),
    ]
