# Generated by Django 3.1.5 on 2021-03-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0001_initial'),
        ('AdminPage', '0003_auto_20210329_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantcourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginPage.kvantteacher'),
        ),
    ]
