# Generated by Django 3.1.5 on 2022-08-09 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantlesson',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
