# Generated by Django 3.1.5 on 2022-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvantlesson',
            name='task',
        ),
        migrations.AddField(
            model_name='kvantlesson',
            name='task',
            field=models.ManyToManyField(blank=True, to='DiaryApp.KvantHomeTask'),
        ),
    ]
