# Generated by Django 3.1.5 on 2022-02-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0002_auto_20220223_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvantlesson',
            old_name='task',
            new_name='tasks',
        ),
    ]
