# Generated by Django 3.1.5 on 2022-03-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0002_auto_20220327_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvanttaskbase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
