# Generated by Django 3.1.5 on 2022-03-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0003_auto_20220327_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kvantlesson',
            options={'ordering': ['date', '-id']},
        ),
    ]
