# Generated by Django 3.1.5 on 2022-07-19 19:35

import AdminApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KvantCourseShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=20)),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'course_shedule',
            },
        ),
        migrations.CreateModel(
            name='KvantCourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=AdminApp.models.getCoursePath)),
            ],
            options={
                'db_table': 'course_type',
            },
        ),
        migrations.CreateModel(
            name='KvantCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('schedule', models.ManyToManyField(to='AdminApp.KvantCourseShedule')),
                ('students', models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.kvantcoursetype')),
            ],
            options={
                'db_table': 'kvant_course',
            },
        ),
    ]
