# Generated by Django 3.1.5 on 2021-06-01 11:54

import LoginApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantuser',
            name='image',
            field=models.ImageField(default=LoginApp.models.set_default_image, upload_to=LoginApp.models.get_path),
        ),
    ]
