# Generated by Django 3.1.5 on 2021-05-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0007_auto_20210509_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvantuser',
            name='image',
        ),
    ]
