# Generated by Django 3.1.5 on 2021-05-09 04:35

import LoginApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemModule', '0001_initial'),
        ('LoginApp', '0009_kvantuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvantuser',
            name='image',
            field=models.ForeignKey(default=LoginApp.models.set_default_image, on_delete=models.SET(LoginApp.models.set_default_image), to='SystemModule.imagestorage'),
        ),
    ]
