# Generated by Django 3.1.5 on 2022-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0003_auto_20220808_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='school_class',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
