# Generated by Django 3.1.5 on 2022-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0004_auto_20220808_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpersonalinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studydocument',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
