# Generated by Django 3.1.5 on 2022-08-08 10:23

import RegisterApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0005_auto_20220808_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpersonalinfo',
            name='snils',
            field=models.CharField(blank=True, max_length=255, validators=[RegisterApp.validators.validate_snils]),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='school_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='snils',
            field=models.CharField(blank=True, max_length=255, validators=[RegisterApp.validators.validate_snils]),
        ),
    ]
