# Generated by Django 3.1.5 on 2022-08-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0007_auto_20220808_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparent',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
