# Generated by Django 3.1.5 on 2022-08-10 09:04

import RegisterApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0008_auto_20220808_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitydocument',
            name='given_date',
            field=models.CharField(blank=True, max_length=255, validators=[RegisterApp.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='staffpersonalinfo',
            name='date',
            field=models.CharField(blank=True, max_length=255, validators=[RegisterApp.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='date',
            field=models.CharField(blank=True, max_length=255, validators=[RegisterApp.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='date',
            field=models.CharField(blank=True, max_length=255, validators=[RegisterApp.validators.validate_date]),
        ),
    ]
