# Generated by Django 3.1.5 on 2022-08-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0010_tempregisterlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempregisterlink',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
