# Generated by Django 3.1.5 on 2022-08-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0012_staffdocumentfiles_studentdocumentfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdocumentfiles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentdocumentfiles',
            name='user',
        ),
        migrations.AddField(
            model_name='staffpersonalinfo',
            name='scans',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.staffdocumentfiles'),
        ),
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='scans',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegisterApp.studentdocumentfiles'),
        ),
    ]
