# Generated by Django 3.1.5 on 2022-08-15 13:21

import RegisterApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0013_auto_20220815_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScanSaveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='staffdocumentfiles',
            name='document',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='staffdocumentfiles',
            name='snils',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='staffdocumentfiles',
            name='surname_change',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='agreement',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='application',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='document',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='father_document',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='mother_document',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='pfdo',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='registration',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
        migrations.AlterField(
            model_name='studentdocumentfiles',
            name='snils',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
    ]
