# Generated by Django 3.1.5 on 2022-08-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0014_auto_20220815_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentScanSaveForm',
        ),
    ]
