# Generated by Django 3.1.5 on 2022-08-15 14:50

import RegisterApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0015_delete_studentscansaveform'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocumentfiles',
            name='study',
            field=models.FileField(blank=True, upload_to=RegisterApp.models.uploadPath),
        ),
    ]
