# Generated by Django 3.1.5 on 2021-05-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvantmessage',
            old_name='task',
            new_name='text',
        ),
    ]
