# Generated by Django 3.1.5 on 2021-06-13 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MailApp', '0002_auto_20210611_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='mailreceiver',
            name='is_important',
        ),
        migrations.AlterField(
            model_name='kvantmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MailSender',
        ),
        migrations.AddField(
            model_name='importantmail',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailApp.kvantmessage'),
        ),
        migrations.AddField(
            model_name='importantmail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
