# Generated by Django 3.1.5 on 2021-05-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0002_auto_20210507_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
