# Generated by Django 3.1.5 on 2021-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0003_kvantmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantmessage',
            name='title',
            field=models.CharField(default='Письмо', max_length=120),
        ),
    ]
