# Generated by Django 3.1.5 on 2021-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0004_kvantmessage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvantmessage',
            name='style_text',
            field=models.TextField(blank=True),
        ),
    ]
