# Generated by Django 3.1.5 on 2021-05-16 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MailApp', '0005_kvantmessage_style_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvantmessage',
            name='receiver',
        ),
        migrations.AddField(
            model_name='kvantmessage',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
