# Generated by Django 3.1.5 on 2021-05-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailApp', '0006_auto_20210516_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvantmessage',
            old_name='receiver',
            new_name='receivers',
        ),
    ]
